/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/$user'
import { Route as IndexImport } from './routes/index'
import { Route as UserAboutImport } from './routes/$user/about'
import { Route as UserPicturesFolderImport } from './routes/$user/pictures/$folder'

// Create/Update Routes

const UserRoute = UserImport.update({
  path: '/$user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserAboutRoute = UserAboutImport.update({
  path: '/about',
  getParentRoute: () => UserRoute,
} as any)

const UserPicturesFolderRoute = UserPicturesFolderImport.update({
  path: '/pictures/$folder',
  getParentRoute: () => UserRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$user': {
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/$user/about': {
      preLoaderRoute: typeof UserAboutImport
      parentRoute: typeof UserImport
    }
    '/$user/pictures/$folder': {
      preLoaderRoute: typeof UserPicturesFolderImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  UserRoute.addChildren([UserAboutRoute, UserPicturesFolderRoute]),
])

/* prettier-ignore-end */
